# Generated by Django 2.1.7 on 2019-02-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_valid',
            new_name='available',
        ),
    ]
